name: Allvao Otomatik Yayinlama

on:
  push:
    branches:
      main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Kodlari Al
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Node.js Kur ve Build Yap
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: ğŸ“¦ Paketleri Yukle
        run: npm install

      - name: ğŸ”¨ Projeyi Derle (Build)
        run: npm run build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }} # Kasadaki anahtarÄ± robota verdik

      - name: ğŸš€ Spaceship (allvao_app) Sunucusuna IsÄ±nla
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./allvao_app/